### ISSUE TITLE
Firebase

### ISSUE THREAD

**Issue by fyznbyr** [Mertaince/FirebaseAuth-SignIn-SignOut-CreateUser-ExampleApp#1]
Firebase configure yapmak gerekir mi?

**Comment by Mertaince** [comment]
Hayir proje içerisinde tüm bağlantılar saglanmistir sadece Firebase yeni proje oluşturup iOS projesini seçip uygulamaya bağlayıp Google.plist dosyasını uygulamanın içerisine atmanız yeterlidir.
